import { type Edge, type Node } from "reactflow";

export type FlowRoute = {
  when?: Record<string, unknown>;
  gotoFlow?: string;
  goto?: string;
  gotoId?: string;
  toMainMenu?: boolean;
  isGoBack?: boolean;
  goBackTarget?: string;
  goBackTargetId?: string;
  goBackToFlow?: string;
};

export type FlowNode = {
  id: string;
  name?: string;
  type: string;
  functionName?: string;
  args?: Record<string, unknown>;
  saveAs?: string;
  message?: string;
  responseFormat?: "json" | "soap" | "ussd";
  responseBodyMapping?: Record<string, unknown>;
  responseBodyRaw?: string;
  responseHeaders?: Record<string, unknown>;
  responseStatusCode?: number;
  sessionMode?: "required" | "optional" | "disabled";
  persistByIndex?: boolean;
  persistByIndexValue?: string;
  persistSourceField?: string;
  persistFieldName?: string;
  validateIndexedList?: boolean;
  indexedListVar?: string;
  invalidInputMessage?: string;
  emptyInputMessage?: string;
  inputType?: "NON_ZERO_FLOAT" | "NON_ZERO_INT" | "FLOAT" | "INTEGER" | "STRING";
  invalidInputTypeMessage?: string;
  inputValidationEnabled?: boolean;
  persistInput?: boolean;
  persistInputAs?: string;
  saveSessionStep?: boolean;
  sessionStepSessionId?: string;
  script?: string;
  timeoutMs?: number;
  scriptRoutes?: Array<{ key?: string; goto?: string; gotoId?: string; gotoFlow?: string }>;
  endpoint?: string;
  url?: string;
  method?: string;
  curl?: string;
  wsCurl?: string;
  requestSource?: "api" | "local" | "ws";
  wsUrl?: string;
  wsProtocols?: string[];
  wsMessage?: string;
  wsLastMessage?: string;
  dataSource?: string;
  field?: string;
  outputVar?: string;
  fields?: string[];
  outputVars?: string[];
  format?: "indexedList" | "singleValue";
  headers?: Record<string, unknown>;
  apiBody?: Record<string, unknown>;
  apiBodyRaw?: string;
  bodyMode?: "json" | "soap" | "form";
  responseMapping?: Record<string, unknown>;
  persistResponseMapping?: boolean;
  maskedResponseMappingKeys?: string[];
  commonManagerResponseMappingKeys?: string[];
  persistManager?: "inputManager" | "commonManager";
  inputManagerSaveSessionId?: string;
  inputManagerFetchSessionId?: string;
  commonManagerSaveMode?: "flowSession" | "provided" | "generate";
  commonManagerSaveSessionId?: string;
  commonManagerSessionOutputVar?: string;
  commonManagerFetchMode?: "session" | "search";
  commonManagerFetchSessionId?: string;
  commonManagerSearchField?: string;
  commonManagerSearchValue?: string;
  encryptInput?: boolean;
  responseType?: "CONTINUE" | "END";
  nextNode?: string | { routes?: FlowRoute[]; default?: string; defaultId?: string; defaultFlow?: string };
  nextNodeId?: string;
  isMainMenu?: boolean;
};

export type FlowJson = {
  flowName: string;
  entryNode: string;
  entryNodeId: string;
  nodes: FlowNode[];
  visualState?: {
    nodes: Node[];
    edges: Edge[];
  };
};
